### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by 2010person**
This new README.md provides more clarification and GoneRogue links. More policies coming soon. Please approve @werdl @uimaxbai @thisiscoding1234 .

### CODE REVIEW

**Review by binimum — APPROVED** [review]
Nice touch, thanks!

**Comment by uimaxbai** [comment]
But can I ask why you have created a pull request for your own repo?

**Comment by binimum** [comment]
Can we please move the discussion from this repo to the one that I have forked under the organisation? Thanks

**Comment by 2010person** [comment]
I can create a pull request to merge the latest changes rom this repo to GoneRogue, archive this for a couple of days, and delete it when we are sure we don't need it.

**Comment by 2010person** [comment]
Created the pull request here: https://github.com/GoneRogueProductions/dispatch_policies/pull/1/ .

**Pull request merged**
